spin_manifest_version = "1"
authors = ["Gerard CL <gerardcl@gmail.com>"]
description = "Blog about tech and such by the people from Can Sixt"
name = "cansixt-blog"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "cansixt-blog"
files = [ { source = "public", destination = "/" } ]
environment = { CUSTOM_404_PATH = "404.html", FALLBACK_PATH = "404.html" }
[component.trigger]
route = "/..."

# [[component]]
# id = "test"
# source = "target/wasm32-wasi/release/test.wasm"
# allowed_http_hosts = []
# [component.trigger]
# route = "/..."
# [component.build]
# command = "cargo build --target wasm32-wasi --release"
# watch = ["src/**/*.rs", "Cargo.toml"]
