name: Zola build and Spin deploy

on:
  push:
    branches:
      - main

jobs:
  zola_build_and_spin_deploy:
    runs-on: ubuntu-latest
    name: Zola build and Spin deploy
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2

      - name: Zola build
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          CHECK_LINKS: false

      - name: Install Rust with WASM toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.82
          targets: wasm32-wasi

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        # with:
          # version: "v0.10.1"

      - name: Spin build and deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          # version: "v0.10.1"
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
